name: Build

on:
  # push:
  #   branches:
  #     - main
  pull_request:
    branches:
      - main

jobs:
  build:
    name: Build on push
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@master

      - name: Build project
        run: |
          git update-index --chmod=+x hack/changelog.sh
          git update-index --chmod=+x hack/version.sh
          make build-in-docker